name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger the action when you push to the 'main' branch
  pull_request:
    branches:
      - main # Trigger when there's a PR to 'main'

jobs:
  build:
    runs-on: windows-latest # Use Windows environment for this job

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (ensure version is compatible)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Change to the version you're using (make sure it's 16 or above)

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project
      - name: Build the project
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for deployment
